### ISSUE TITLE
ember-version-checker appears to need bumped (trying ember-cli@v2.11.0-beta.1)

### ISSUE THREAD

**Issue by efx** [alphasights/ember-scrollable#36]
ember build is failing in my project when I have upgraded to ember-cli@v2.11.0-beta.1:
```
ember build -w t
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-get-helper`
    at Function.Addon.lookup (fakepath/node_modules/ember-cli/lib/models/addon.js:996:27)
⠋ BuildingInvalid Version: undefined
TypeError: Invalid Version: undefined
    at new SemVer (fakepath/node_modules/ember-scrollable/node_modules/semver/semver.js:281:11)
    at compare (fakepath/node_modules/ember-scrollable/node_modules/semver/semver.js:571:10)
    at Function.lt (fakepath/node_modules/ember-scrollable/node_modules/semver/semver.js:605:10)
    at DependencyVersionChecker.(anonymous function) [as lt] (fakepath/node_modules/ember-scrollable/node_modules/ember-cli-version-checker/index.js:68:26)
    at Class.treeFor (fakepath/node_modules/ember-scrollable/index.js:27:31)
    at Class.superWrapper [as treeFor] (fakepath/node_modules/ember-cli/node_modules/core-object/lib/assign-properties.js:32:18)
    at fakepath/node_modules/ember-cli/lib/models/addon.js:245:34
    at Array.map (native)
    at Class.eachAddonInvoke (fakepath/node_modules/ember-cli/lib/models/addon.js:243:24)
    at Class.treeFor (fakepath/node_modules/ember-cli/lib/models/addon.js:329:22)
```
I'll try to isolate this to make sure it is that package

**Comment by luketheobscure** [comment]
Might be worth releasing this. Getting errors in my projects because they have dependencies on this.
